### ISSUE TITLE
UI Issues to fix

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#22]
- [x] Add scrolling inertia to timetable 
- [x] Correctly handle network instability when posting forum posts
- [x] Implement `Canteen crowdedness summary` for other campuses.
- [x] Implement "double tap the top bar to return to the top" and add scroll bar on mobile devices (like native implementations)
- [x] Implement preloading on QR Code and Forum posts
- [x] Display a loading indicator when loading forum posts and replies
- [x] **Reduce the amount of text on dashboard (mainly concerning Summary)** switch to a tag-based summary, like `[排队最多]北区餐厅` _(can we have graphical tags?)_
- [x] Fix iOS animation/UI inconsistency (switch to `CupertinoSliverNavigationBar`?)
- [x] Dark Mode Support _(scheduled after first release)_

**Comment by w568w** [comment]
>  Add scrolling inertia to timetable
>   Implement "double tap the top bar to return to the top"
>   Implement preloading on QR Code and Forum posts
>  Display a loading indicator when loading forum posts and replies
>  Reduce the amount of text on dashboard (mainly concerning Summary) switch to a tag-based summary,

🚀 Work on very soon

>   Implement Canteen crowdedness summary for other campuses.
>  Dark Mode Support

❓   Low priority

**Comment by w568w** [comment]
>     Implement preloading on QR Code and Forum posts

Since QR code is generated by Fudan server, we don't know the frequency or time it refreshes. Also, most of the users will use QR code as soon as the app starts, so **there's no need to preload QR code.** It will slow down the retrieval of other information too.  

We're to change the forum source provider, so any plan about improving our temporary forums should be cancelled.
