### ISSUE TITLE
[Feature Request] not show the floor widget if floor content is empty

### ISSUE THREAD

**Issue by JingYiJun** [DanXi-Dev/DanXi#343]
above

**Comment by w568w** [comment]
Can you elaborate why it is useful, or at least give an example?

**Comment by JingYiJun** [comment]
User may find too many floors with empty content, thus bad user experience

**Comment by JingYiJun** [comment]
Also, a floor with sensitive content should not be liked or reply directly on UI

**Comment by w568w** [comment]
> User may find too many floors with empty content

Wait, why? Why will there be "too many empty floors"? What exactly is the backend going to return in the future changes?

> a floor with sensitive content should not be liked or reply directly on UI

So "a floor with sensitive content = empty floor"? 

I think it's better to add a special field in the post for that, e.g. `is_sensitive`. 

It is not a sound way that simply hides all empty floors, since in my opinion "empty floor != floor with sensitive content".
